server.py
Utilize LlamaTokenizer/LlamaModelForCausalLM and use device_map='auto' for faster loading
=> Optimize model load

schema.py
looks like my local pydantic and server pydantic misaligned
=> Use dict instead of model_dump for back compatibility with pydantic v1 vs v2

functionary/inference.py, functionary/inference_stream.py, functionary/openai_types.py, server.py
+ Add streaming feature by just adding an additional parameter: stream=True/False default = False
+ The steaming output has the same format like the output from OpenAI (Already tested)
=> Add streaming feature

functionary/inference_stream.py, functionary/openai_types.py, server.py
+ Fix the format of the returned json for non-streaming
+ Fix the format of the returned json for streaming
Mostly, fixing the format here is just removing unnecessary **Null fields**
=> fix the output format to match that of openAI exclusively

train/README.md, train/custom_datasets.py, train/train.py
- `preprocess_logits_for_metrics`  function to reduce CPU memory requirements during evaluation
- accuracy and loss evaluation implementation
=> Compute metrics

functionary/inference.py
+ Implement stopping criteria for hitting predefined words, phrases
=> add stopping criteria for hitting words in inference

functionary/train/README.md, functionary/train/fsdp_config.yaml, functionary/train/llama_flash_attn_monkey_patch.py, functionary/train/train.py
- set `fsdp.use_orig_params=True` for paged_adamw_32bit to work
- updated train dependencies
- updated llama flash attn monkey patch
- removed data shuffling during loading
- update final checkpoint saving to always use `fsdp.FULL_STATE_DICT` mode
=> Refactor training

functionary/inference.py, functionary/inference_stream.py, functionary/prompt.py, server_vllm.py
+ fix inference for new model: stream and non-stream in server.py; non-stream in server_vllm.py
=> fix inference for new model

functionary/schema.py
Currently:
"x": {"type": "integer", "enum": [1,2,3]} --> x: "1" | "2" | "3"
This PR will fix this: --> x: 1 | 2 | 3
=> Fix the issue when a parameter is enum with type != string

functionary/inference.py, functionary/openai_types.py, functionary/prompt_template/base_template.py, functionary/prompt_template/prompt_template_v2.py, functionary/vllm_monkey_patch/async_llm_engine.py, server_vllm.py
- Added `add_predefined_fns` flag in `gen_state` which lets us know whether to add predefined function names (e.g.: all) to the list of function names for grammar sampling
=> Implement tool_choice option

functionary/train/packing/README.md, functionary/train/packing/monkey_patch_packing.py, functionary/train/train.py, functionary/train/train_lora.py
+ Activate adding load_balancing_loss to loss computation in training Mixtral
+ Update monkeypatch for packing Mixtral (HF updated computing load balanching loss)
=> Activate load_balanching_loss in training Mixtral + fix packing for Mixtral

functionary/prompt_template/base_template.py, functionary/train/README.md, functionary/train/custom_datasets.py, tests/prompt_test_v2.txt, tests/test_case_v2.json, tests/test_prompt_creation.py
+ add option for masking assistant message or not 
+ update versions of accelerate, transformers
=> Add masked assistant indices in training

functionary/train/custom_datasets.py, functionary/train/train.py, functionary/train/train_lora.py
+ Change the location of cached_folder outside output_dir
+ removing computing metrics for Mixtral (if not will encounter errors)
=> change the location of cached_folder and remove computing metrics for Mixtral

server.py
Reverts MeetKai/functionary#166
=> Revert "Delete server.py"

functionary/vllm_monkey_patch/async_llm_engine.py, requirements.txt, server_vllm.py, tests/test_prompt_creation.py
Upgrade vLLM to source version
=> Upgrade vllm

README.md, functionary/inference.py, functionary/prompt_template/__init__.py, functionary/prompt_template/base_template.py, functionary/prompt_template/llama3_prompt_template.py, functionary/prompt_template/prompt_template_v2.py, functionary/prompt_template/prompt_utils.py, functionary/vllm_inference.py, functionary/vllm_monkey_patch/async_llm_engine.py, tests/test_request_handling.py
- Test edge cases error raising
- Test response creation for non-streaming
- Fix discovered small bugs
- `tool_calls` returns `None` instead of empty string now
- inference handles `request.function_call` if it is not None
=> Add unittest for testing request-handling

functionary/train/README.md, functionary/train/metrics.py, functionary/train/train_utils.py, functionary/train_vision/README.md, functionary/train_vision/train.py, requirements.txt, tests/test_metrics.py
+ add computing the accuracy of predicting the first token in all arguments in training steps and evaluation steps
+ fix only compute training metrics in training loop, not evaluation loop
=> Add metric for arguments in training

README.md
+ Add new model: meetkai/functionary-small-v3.1 to readme
=> Add new model: meetkai/functionary-small-v3.1. to the readme

functionary/prompt_template/__init__.py, functionary/prompt_template/base_template.py
fix function get_prompt_template from tokenizer by checking jinja prompt template
=> fix function get_prompt_template from tokenizer

functionary/prompt_template/__init__.py, functionary/prompt_template/jinja_templates/v3-llama3.1-reasoning.txt, functionary/prompt_template/llama31_reasoning_prompt_template.py, tests/test_request_handling.py
+ Add prompt template for reasoning models
=> add prompt template for reasoning

README.md, functionary/sglang_inference.py, functionary/sglang_monkey_patch/tokenizer_manager.py, pyproject.toml, server_sglang.py
+ Migrate to newest sglang version 
+ Support n-sampling
=> Migrate sglang + support n-sampling
